version: "3.9"
services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
volumes:
  mongo_data:
  mongo_config:
